apiVersion: v1
kind: Service
metadata:
  name: memberships
  namespace: courtside
  labels:
    app: memberships
spec:
  selector:
    app: memberships
  ports:
    - name: http
      port: 8080
      targetPort: http
