apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-eso
  namespace: courtside
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-from-vault
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: courtside/postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: courtside/postgres
        property: POSTGRES_PASSWORD
