name: notifications
image:
  repository: ghcr.io/quasar0x/courtside-notifications
  tag: "38f15d83b12e7f7e9b4e84e02b5da70f80e9ff2e"
  digest: "sha256:4bae864e97f8f14443a317ecb85705f40eeee33a51578ba340c790f87fcfc79a"
env:
  - name: PORT
    value: "8080"
  - name: KAFKA_BROKER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_BROKER
  - name: KAFKA_USER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_USER
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_PASSWORD
  - name: KAFKA_CA_PEM
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_CA_PEM
  - name: REDIS_ADDR
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_ADDR
  - name: REDIS_USER
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_USER
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_PASSWORD
  - name: REDIS_CA_PEM
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_CA_PEM
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
