name: notifications
image:
  repository: ghcr.io/quasar0x/courtside-notifications
  tag: "38f15d83b12e7f7e9b4e84e02b5da70f80e9ff2e"
  digest: "sha256:4bae864e97f8f14443a317ecb85705f40eeee33a51578ba340c790f87fcfc79a"
env:
  - name: PORT
    value: "8080"
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: REDIS_ADDR
    value: "redis:6379"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
