name: clubs
image:
  repository: ghcr.io/quasar0x/courtside-clubs
  tag: "510889787cd6536703bfee8ffbc547b19fc17247"
  digest: "sha256:0e1539f26a647527725b341efa4c1e6bb05d80cd0391112372176ceb5071aee5"
env:
  - name: PORT
    value: "8080"
  - name: MEMBERS_URL
    value: "http://members:8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "clubs"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
