name: memberships
image:
  repository: ghcr.io/quasar0x/courtside-memberships
  tag: "53baebd806836daf4a9679ff3f328cb52bf1c613"
  digest: "sha256:c200d3ccd8281f9b16e10c07c5e755b3451c3d406ed3554e057b98ea2eb1b9fe"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "memberships"
  - name: KAFKA_BROKER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_BROKER
  - name: KAFKA_USER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_USER
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_PASSWORD
  - name: KAFKA_CA_PEM
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_CA_PEM
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
