name: notifications
image:
  repository: ghcr.io/quasar0x/courtside-notifications
  tag: "510889787cd6536703bfee8ffbc547b19fc17247"
  digest: "sha256:e56cb5e55a977a13c61a2e273fa8d125e5e9333d45f91df4723f2d152243ffc9"
env:
  - name: PORT
    value: "8080"
  - name: KAFKA_BROKER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_BROKER
  - name: KAFKA_USER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_USER
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_PASSWORD
  - name: KAFKA_CA_PEM
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_CA_PEM
  - name: REDIS_ADDR
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_ADDR
  - name: REDIS_USER
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_USER
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_PASSWORD
  - name: REDIS_CA_PEM
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_CA_PEM
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
