name: clubs
image:
  repository: ghcr.io/quasar0x/courtside-clubs
  tag: "8c8d3fe3a01267ab6109bb8accdded65274070be"
env:
  - name: PORT
    value: "8080"
  - name: MEMBERS_URL
    value: "http://members:8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "clubs_staging"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
