name: notifications
image:
  repository: ghcr.io/quasar0x/courtside-notifications
  tag: "53baebd806836daf4a9679ff3f328cb52bf1c613"
  digest: "sha256:e6159a1154891ab8e2ec4c3a49a7eb70ba2837e5dea0605ff18945aeba2de2b1"
env:
  - name: PORT
    value: "8080"
  - name: KAFKA_BROKER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_BROKER
  - name: KAFKA_USER
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_USER
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_PASSWORD
  - name: KAFKA_CA_PEM
    valueFrom:
      secretKeyRef:
        name: kafka
        key: KAFKA_CA_PEM
  - name: REDIS_ADDR
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_ADDR
  - name: REDIS_USER
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_USER
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_PASSWORD
  - name: REDIS_CA_PEM
    valueFrom:
      secretKeyRef:
        name: valkey
        key: REDIS_CA_PEM
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
