name: notifications
image:
  repository: ghcr.io/quasar0x/courtside-notifications
  tag: "9c3d7540c6430be7d1bd591fbee95ae88fecc874"
  digest: "sha256:67e3f57cd24c22ad8f4c0a1a0df19cf21b3118cb8d4dded14b631ed428335d4b"
env:
  - name: PORT
    value: "8080"
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: REDIS_ADDR
    value: "redis:6379"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
