name: members
image:
  repository: ghcr.io/quasar0x/courtside-members
  tag: "9c3d7540c6430be7d1bd591fbee95ae88fecc874"
  digest: "sha256:bbc84e6d040a40530905cc1814b5e203343e95fb608d1b407bb352d7d2ef5e29"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "members_staging"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
