name: billing
image:
  repository: ghcr.io/quasar0x/courtside-billing
  tag: "9c3d7540c6430be7d1bd591fbee95ae88fecc874"
  digest: "sha256:96abece423c6f314553a59ca633fc7ab84c765924e6e2db110c825801adb6e02"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "billing_staging"
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: REDIS_ADDR
    value: "redis:6379"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
