name: billing
image:
  repository: ghcr.io/quasar0x/courtside-billing
  tag: "c11b6e4d969d91f86b64204c2e74c06e43ea18c3"
  digest: "sha256:1e196d939650a132ccae718a97a8499cca14fd1f2708f8dc04efcee5f0ab877d"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "billing_staging"
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: REDIS_ADDR
    value: "redis:6379"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
