name: members
image:
  repository: ghcr.io/quasar0x/courtside-members
  tag: "9c3ba7aaae50d70114fe3cc923a55acace31a681"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "members_staging"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
