name: memberships
image:
  repository: ghcr.io/quasar0x/courtside-memberships
  tag: "38f15d83b12e7f7e9b4e84e02b5da70f80e9ff2e"
  digest: "sha256:408a8f570cc7cda1902ba95abf93044dd08ebab5560b15afc6b492365807368f"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "memberships_staging"
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
