name: memberships
image:
  repository: ghcr.io/quasar0x/courtside-memberships
  tag: "9c3d7540c6430be7d1bd591fbee95ae88fecc874"
  digest: "sha256:f0f756747fd7e9f4644dc9fc7d53a24d8ce4052c242cc609478b794d6d5a5578"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "memberships_staging"
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
