name: clubs
image:
  repository: ghcr.io/quasar0x/courtside-clubs
  tag: "53baebd806836daf4a9679ff3f328cb52bf1c613"
  digest: "sha256:cb28675fe89778ff71310fd4ef317ecd58e8c22e39f1f7f78bbc956c0f3c46ca"
env:
  - name: PORT
    value: "8080"
  - name: MEMBERS_URL
    value: "http://members:8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "clubs_staging"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
