name: notifications
image:
  repository: ghcr.io/quasar0x/courtside-notifications
  tag: "53baebd806836daf4a9679ff3f328cb52bf1c613"
  digest: "sha256:e6159a1154891ab8e2ec4c3a49a7eb70ba2837e5dea0605ff18945aeba2de2b1"
env:
  - name: PORT
    value: "8080"
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: REDIS_ADDR
    value: "redis:6379"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
