name: members
image:
  repository: ghcr.io/quasar0x/courtside-members
  tag: "c11b6e4d969d91f86b64204c2e74c06e43ea18c3"
  digest: "sha256:f4d494b5552bc0836350ed5726fab25bfd1828fab8d86617e2c9577a4a33132d"
env:
  - name: PORT
    value: "8080"
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGHOST
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPORT
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGUSER
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGPASSWORD
  - name: PGSSLMODE
    valueFrom:
      secretKeyRef:
        name: postgres
        key: PGSSLMODE
  - name: PGDATABASE
    value: "members_staging"
  - name: OTEL_ENDPOINT
    value: "otel-collector.monitoring:4318"
