apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-data
  namespace: residency-us
  labels: { app: us-data }
spec:
  replicas: 1
  selector: { matchLabels: { app: us-data } }
  template:
    metadata: { labels: { app: us-data, region: us-east } }
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: [us-east]
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports: [{ containerPort: 80 }]
