apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-clubs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quasar0x/courtside.git
    targetRevision: main
    path: gitops/base/service
    helm:
      valueFiles:
        - values-clubs.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: courtside
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
