prometheus:
  prometheusSpec:
    retention: 2h
    scrapeInterval: 30s
    resources:
      requests:
        cpu: 100m
        memory: 350Mi
      limits:
        memory: 800Mi
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  adminPassword: admin
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      memory: 384Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 128Mi

prometheus-node-exporter:
  resources:
    limits:
      memory: 64Mi

kube-state-metrics:
  resources:
    limits:
      memory: 128Mi
