apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/quasar0x/courtside.git
    targetRevision: main
    path: deploy
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: courtside
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
